Change device name and id
AaronDavidSchneider/SonosAlarm pull request #25
Opened 2021-04-20 08:27 UTC by rasmusbe

I looked at the recent changes you did and noticed that every alarm became a different device.
This PR fixed that partially, with one drawback.

Pros:
- All alarms for one speaker is grouped to the same device
- Nicer names for the devices

Cons:
- When an alarm is moved to another speaker a restart is needed to move the entity to the correct device (since `device_info` cannot be updated). But the entity name will be updated directly so it shouldn't be a big problem.

I'm thinking that keeping the entities together in the correct device is a bigger win than the drawback of getting the devices completely correct without a restart.

2021-04-20 08:42 UTC, AaronDavidSchneider commented
Hi @rasmusbe,

Thanks for taking the time to review!
Yes I had the same idea at first. My first idea was to use even the same device_info like the sonos integration does.

I then went for the other solution since the devices will only get removed when you readd the integration.

Here is an example of how it then would look like after a few room changes.

![Bildschirmfoto 2021-04-20 um 10 38 56](https://user-images.githubusercontent.com/7556347/115365380-9e835080-a1c4-11eb-87d7-963b23f94868.png)
Note: Ignore the lowest row.

Here again the advantage of grouping the devices together in line with the core sonos integration:
![Uploading Bildschirmfoto 2021-04-20 um 10.42.11.png…]()

2021-04-20 08:48 UTC, AaronDavidSchneider requested changes
This is how you can change it to bring it in line with the sonos core integration. This is also commented in the lines above.

2021-04-20 08:48 UTC, AaronDavidSchneider commented on custom_components/sonos_alarm/switch.py
>          }
```suggestion
    def device_info(self) -> dict:
        """Return information about the device."""
        return {
            "identifiers": {(SONOS_DOMAIN, self._unique_player_id)},
            "name": self._speaker_name,
            "model": self._model.replace("Sonos ", ""),
            "sw_version": self._sw_version,
            "connections": {(dr.CONNECTION_NETWORK_MAC, self._mac_address)},
            "manufacturer": "Sonos",
            "suggested_area": self._speaker_name,
        }
```

2021-04-20 14:27 UTC, AaronDavidSchneider approved these changes

2021-04-20 14:29 UTC, AaronDavidSchneider commented
I am currently discussing the issue of device updates on discord. I would say that we merge it once we are able to deal with the rubbish that this merge will create upon room changes.

2021-04-20 17:25 UTC, rasmusbe commented
Sounds good, I'm trying out some stuff randomly to make it better as well, but no luck yet

2021-04-21 05:53 UTC, AaronDavidSchneider commented
I think I fixed it :D

So first of all, we can clean up old devices in the __init__.py once entries are (re)created (e.g. after a restart of hass):
(I got this from the plex integration)

```python
async def async_setup_entry(hass, entry):
    """Set up Sonos from a config entry."""
    for domain in [SWITCH_DOMAIN]:
        hass.async_create_task(
            hass.config_entries.async_forward_entry_setup(entry, domain)
        )
    async_cleanup_sonos_devices(hass, entry)
    return True


@callback
def async_cleanup_sonos_devices(hass, entry):
    """Clean up old and invalid devices from the registry."""
    device_registry = dr.async_get(hass)
    entity_registry = er.async_get(hass)

    device_entries = hass.helpers.device_registry.async_entries_for_config_entry(
        device_registry, entry.entry_id
    )

    for device_entry in device_entries:
        if (
                len(
                    hass.helpers.entity_registry.async_entries_for_device(
                        entity_registry, device_entry.id, include_disabled_entities=True
                    )
                )
                == 0
        ):
            device_registry.async_remove_device(device_entry.id)
```

And secondly:
We can switch devices in `switch.py` if we use this function (that I hacked together using some debugging and comments on discord)
```python
    def _update_device(self):
        device_registry = dr.async_get(self.hass)
        entity_registry = er.async_get(self.hass)
        entry_id = entity_registry.async_get(self.entity_id).config_entry_id

        new_device = device_registry.async_get_or_create(config_entry_id=entry_id, identifiers = {(SONOS_DOMAIN, self._unique_player_id)}, connections={(dr.CONNECTION_NETWORK_MAC, self._mac_address)})
        if not entity_registry.async_get(self.entity_id).device_id == new_device.id:
            entity_registry._async_update_entity(self.entity_id, device_id=new_device.id)
```

We may not forget the import statements:
```python
from homeassistant.helpers import device_registry as dr, entity_registry as er
from homeassistant.core import callback  #only needed for __init__.py
```

Do you want to add the changes? Or should I open up a new PR? I would love to hear if that changes also work for you!

2021-04-21 06:23 UTC, rasmusbe commented
Awesome! Looks good! Let's open a new PR, if you already have it working I think that's the easiest way. I'll can try it out then 👍

2021-04-21 06:23 UTC, closed without merging